BOOKMAKERS = [
    {"id": 38, "name": "BarrierBet"},
    {"id": 24, "name": "Betclic"},
    {"id": 43, "name": "Betsson"},
    {"id": 23, "name": "Bwin"},
    {"id": 42, "name": "FeelingBet"},
    {"id": 27, "name": "France-Pari"},
    {"id": 32, "name": "Genybet"},
    {"id": 30, "name": "NetBet"},
    {"id": 44, "name": "OlyBet"},
    {"id": 22, "name": "Parions Sport"},
    {"id": 41, "name": "Partouche Sport"},
    {"id": 21, "name": "PMU.fr"},
    {"id": 36, "name": "PokerStars Sports"},
    {"id": 20, "name": "Unibet"},
    {"id": 37, "name": "VBet"},
    {"id": 33, "name": "Winamax"},
    {"id": 34, "name": "ZEbet"},
]

